# Generated by Django 3.0 on 2024-03-03 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_temp', to=settings.AUTH_USER_MODEL),
        ),
    ]
